# Jobs represent one-off tasks that run to completion and then stop.
 # A Job creates one or more Pods and will continue to retry execution of the Pods until a specified number of them successfully terminate.
apiVersion: batch/v1
kind: Job
metadata:
  name: pi
spec:
  template:
    spec:
      containers:
        - name: pi
          image: perl:5.34.0
          command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: Never
  backoffLimit: 4
